### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by mayankraichura** [kleinejan/128bit-shiftregister#1]
Hi, I'm trying to build this PCB but I couldn't identify the size and value of capacitors used. Can you, please, share the BOM? Thanks.

**Comment by kleinejan** [comment]
16 x CAP TANT 10UF 25V 20% 2917 Near the power supply
1 x CAP TANT 100UF 10V 10% 2917
I will try to make an export within Kicad.
If you want I can send you a PCB, have to many :)

--




--

**Comment by kleinejan** [comment]
Added to the repo.
